
apiVersion: v1
kind: Config

clusters:
- name: k3s-cluster
  cluster:
    server: https://192.168.21.100:6443 # est l'adresse du control-plane
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpRMU5UY3pNVFV3SGhjTk1qWXdNekkyTWpBek5URTFXaGNOTXpZd016SXpNakF6TlRFMQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpRMU5UY3pNVFV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSQ2tIaU1memtTVEI5RWZ6WWVRSzNhMjA1NytRSVFacGxhdGpiZmZlUWIKYytuK2FGc3hnWmI3ckFiRlR4WU40cnN4MlRJRVVKcFExQVlicmtYRHdad1hvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWlkUXl6RmVsTHAwSzBHZDAzdnNSCmVIUmp1dWt3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnQXB2bFRSMkorWkFmRXJzK2wzWHZZbjREckliV1V5dzAKWjlocGFUT1llVUVDSUU3WlhLOGZIRm44OWlRSkpIenF6T2YyUm81NU1rV09rZkZqTkVMRUZhQUEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

users:
- name: etudiant
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ino5NUJFRXNvNmdUcjYtV2ZMdF9tVDZuSnRXNUVmR3FSN0pjRUZvbC1CdlkifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzc2MDk3MzQ5LCJpYXQiOjE3NzYwOTM3NDksImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiZDFhOGNlY2YtYzU4Mi00NDVmLWJjY2MtMzdhYTk4MjA2MDI1Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZXYiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZXR1ZGlhbnQtc3J2YWNjb3VudCIsInVpZCI6IjliNzY4MDM2LTk1Y2MtNGM3OS1iMDhhLTZlYjhmMDlmNDQ0NSJ9fSwibmJmIjoxNzc2MDkzNzQ5LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGV2OmV0dWRpYW50LXNydmFjY291bnQifQ.YJ2PKK-Ks0Nm6qRIaTQvBhBAffBMhERpTDBYKBcdbPiYqzMD0Ro8c9tZTow7oCqEKpCsHfG36O9Jn7jk_skXcDs50g3eMTAG9GP2nr4VyUOwzRnrnRowgG3Q4RAEksGFsFdJZcbPnelzrUal4Zbphm8t0JAyR2LeZXrBRtrYnbGFxxgYMz9W5oms9ptEfe_fowOecnSDZ_3dtRHY7VmFskp4BN6l9PB-wb2ELTyRIvAdUUbvDJwAwirnSX3VyuhQvcBIqGSTIP3xNHeS8UkzWTM8P8ypJxzAosZtkFtBxjgFlU5ZMkrVWphw7cCY8XIVB-JrnXEGRdFpP9SFoYPrYA

contexts:
- name: etudiant-context
  context:
    cluster: k3s-cluster
    user: etudiant
    namespace: dev

current-context: etudiant-context
